# Generated by Django 4.2.15 on 2024-08-26 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_o2m_to_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
